### ISSUE TITLE
Add GPP Events | Raid Loot

### ISSUE THREAD

**Issue by VanguardAshkandi** [marisa-ashkandi/vanguard-services#14]
When adding "Raid Loot" events, the  ITEM ID tab is shown as Player Name (For a second time in the form).

Also, when trying to type into that row, it only allows 1 character at a time. You have to reclick the box and type in 1 more character.
![image](https://user-images.githubusercontent.com/55810890/67417413-5020d180-f58e-11e9-81e3-e97ceaa2d35e.png)

**Comment by marisa-ashkandi** [comment]
https://github.com/marisa-ashkandi/vanguard-services/commit/0f53f14e9b64f7599d506a1235115d5bc2821661
