### ISSUE TITLE
GPP Calculation

### ISSUE THREAD

**Issue by VanguardAshkandi** [marisa-ashkandi/vanguard-services#15]
When viewing a user that has exceeded the cap, their current points correctly show via the overall view list that they are indeed capped at 150 points, but upon deeper inspection the point values show themselves true.

Will this affect calculations? Will they be at 150 points on the front end until they have gotten enough loot to go from (example) 500 to 100?

Both should cap at 150.

![image](https://user-images.githubusercontent.com/55810890/67417506-8fe7b900-f58e-11e9-8cc3-aed298d3583d.png)

**Comment by marisa-ashkandi** [comment]
The UI just does a naive sum over all events for this view.  Solution is to pass the summary data, and use that instead.
