### ISSUE TITLE
Upload Raid Failure

### ISSUE THREAD

**Issue by VanguardAshkandi** [marisa-ashkandi/vanguard-services#18]
Uploading Raid files fail.

![image](https://user-images.githubusercontent.com/55810890/67419372-35505c00-f592-11e9-9fc6-9b518d1f2ffd.png)

**Comment by marisa-ashkandi** [comment]
Errors should be properly surfaced in the UI as of:

https://github.com/marisa-ashkandi/vanguard-services/commit/3dbce0797263a8068c20e6b66007aab1bb1331e6
https://github.com/marisa-ashkandi/vanguard-services/commit/96a3fed143b9deb0e0838012e69f66811bc36d55
