### ISSUE TITLE
Transfer Assets

### ISSUE THREAD

**Issue by VanguardAshkandi** [marisa-ashkandi/vanguard-services#26]
So, just having an idea.. may be thrown in the !wontfix category, **BUT**:

I thought about if we utilize Vanguardbank as the asset control for all of the BoEs?
I didnt realize that that character was used as housing for all of the BoEs, so it would be neat if there was a transfer button next to the delete/edit icons.
Existing:
![image](https://user-images.githubusercontent.com/55810890/67522322-2e007f80-f672-11e9-94f5-acba9ff4ad1c.png)
Very Crude Example:
![image](https://user-images.githubusercontent.com/55810890/67522681-c860c300-f672-11e9-9779-48698c0bf6bd.png)

And so this would take the JSON data, transfer to *target character* and do ***all the maths***.
This would be better than loot events, and it would neat to be able to see transfers in and out as an event, so that we could see transfer out of vanguardbank to a player, or a transfer from a player to another player (if master loot was misclicked and VRR was misclicked to award the wrong person)

**Comment by marisa-ashkandi** [comment]
I like this a lot.  Has extra uses, too, like loot that gets looted to someone initially and traded between people later.
